---
- name: Create New User
  hosts: hardware
  become: true
  gather_facts: false
  vars:
# Define your username and password here that you want to create on target hosts.
    username: jane
    userpass: sarum
    super_group: sudo
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        groups: "{{ super_group }}"
        append: yes
        